name: Build docs

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-pages:
    runs-on: ubuntu-latest
    env:
      PIP_CACHE_DIR: "${{ github.workspace }}/.cache/pip"
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: actions/cache@v3.3.1
      with:
        path: |-
          .cache/pip
          venv/
        key: default
    - run: apt-get update -qq
    - run: apt-get install gfortran -qq -y
    - run: python --version
    - run: apt-get update -qq && apt-get install -qq -y pandoc
    - run: pip install sphinx sphinxcontrib-images sphinx-rtd-theme==1.2.0
    - run: pip install nbsphinx
    - run: pip install nbsphinx_link
    - run: pip freeze | grep sphinx
    - run: pip install .
    - run: cd docs
    - run: make html
    - uses: actions/upload-artifact@v3.1.1
      if: success()
      with:
        name: "${{ github.job }}"
        path: docs/build/html/
